version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: deployment/docker-image/postgres.Dockerfile
    container_name: todo-db
    ports:
      - 8080:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-alpine
    container_name: todo-redis
    ports:
      - 8081:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 5s
      retries: 5
  # api:
  #   build:
  #     context: .
  #     dockerfile: deployment/docker-image/api.Dockerfile
  #   container_name: todo_api
  #   ports:
  #     - 8082:8082
  #   env_file:
  #     - deployment/env/api.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8082/healthz || exit 1"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  # web:
  #   build:
  #     context: .
  #     dockerfile: deployment/docker-image/web.Dockerfile
  #   container_name: todo_web
  #   ports:
  #     - 8083:8083
  #   env_file:
  #     - deployment/env/web.env
  #   depends_on:
  #     api:
  #       condition: service_healthy
volumes:
  db_data:
  redis_data:
