version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: deployment/docker-image/api.Dockerfile
    container_name: todo_api
    ports:
      - 8082:8082
    env_file:
      - deployment/env/api.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:17
    container_name: todo_db
    ports:
      - 8080:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-alpine
    container_name: todo_redis
    ports:
      - 8081:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: deployment/docker-image/web.Dockerfile
    container_name: todo_web
    ports:
      - 8083:8083
    env_file:
      - deployment/env/web.env
    depends_on:
      - api

volumes:
  db_data:
  redis_data:
